/*
 * keyb_map.h
 * Copyright (C) 2015 by Juan J. Martinez <jjm@usebox.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
*/
#define KEYB_MAX_SCANCODE 0x76
PROGMEM const unsigned char keyb_map[][2] = {
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x09', '\x00' }, 
{ '`', '|' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 'q', 'Q' }, 
{ '1', '!' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 'z', 'Z' }, 
{ 's', 'S' }, 
{ 'a', 'A' }, 
{ 'w', 'W' }, 
{ '2', '"' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 'c', 'C' }, 
{ 'x', 'X' }, 
{ 'd', 'D' }, 
{ 'e', 'E' }, 
{ '4', '$' }, 
{ '3', '\x9c' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x20', '\x00' }, 
{ 'v', 'V' }, 
{ 'f', 'F' }, 
{ 't', 'T' }, 
{ 'r', 'R' }, 
{ '5', '%' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 'n', 'N' }, 
{ 'b', 'B' }, 
{ 'h', 'H' }, 
{ 'g', 'G' }, 
{ 'y', 'Y' }, 
{ '6', '^' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 'm', 'M' }, 
{ 'j', 'J' }, 
{ 'u', 'U' }, 
{ '7', '&' }, 
{ '8', '*' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ ',', '<' }, 
{ 'k', 'K' }, 
{ 'i', 'I' }, 
{ 'o', 'O' }, 
{ '0', ')' }, 
{ '9', '(' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '.', '>' }, 
{ '/', '?' }, 
{ 'l', 'L' }, 
{ ';', ':' }, 
{ 'p', 'P' }, 
{ '-', '_' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x27', '@' }, 
{ 0, 0 }, 
{ '[', '{' }, 
{ '=', '+' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x0a', '\x00' }, 
{ ']', '}' }, 
{ 0, 0 }, 
{ '#', '~' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x5c', '|' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x08', '\x00' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x11', '4' }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ 0, 0 }, 
{ '\x1f', '2' }, 
{ 0, 0 }, 
{ '\x10', '6' }, 
{ '\x1e', '8' }, 
{ '\x1b', '\x00' }
}; // keyb_map ends

